const tracks = [
  {
    'album': {
      'album_type': 'compilation',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/5l3zEmMrOhOzG8d8s83GOL',
      },
      'href': 'https://api.spotify.com/v1/albums/5l3zEmMrOhOzG8d8s83GOL',
      'id': '5l3zEmMrOhOzG8d8s83GOL',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/d8a6239b6b6065b4d04d4f3fc97cbfc752cfd9e7',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/473a3dd985633cb0f5f9cf43b738edf8271fbd09',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/9e194b2cf18bc27fe678e84bc8232da62357979f',
          'width': 64,
        },
      ],
      'name': 'Despicable Me 2 (Original Motion Picture Soundtrack)',
      'type': 'album',
      'uri': 'spotify:album:5l3zEmMrOhOzG8d8s83GOL',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2RdwBSPQiwcmiDo9kixcl8',
        },
        'href': 'https://api.spotify.com/v1/artists/2RdwBSPQiwcmiDo9kixcl8',
        'id': '2RdwBSPQiwcmiDo9kixcl8',
        'name': 'Pharrell Williams',
        'type': 'artist',
        'uri': 'spotify:artist:2RdwBSPQiwcmiDo9kixcl8',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 233305,
    'explicit': false,
    'external_ids': {
      'isrc': 'USQ4E1300686',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6NPVjNh8Jhru9xOmyQigds',
    },
    'href': 'https://api.spotify.com/v1/tracks/6NPVjNh8Jhru9xOmyQigds',
    'id': '6NPVjNh8Jhru9xOmyQigds',
    'name': 'Happy',
    'popularity': 77,
    'preview_url': 'https://p.scdn.co/mp3-preview/609cf640a652b3ca4d22b1d604f0885b7a591af9',
    'track_number': 4,
    'type': 'track',
    'uri': 'spotify:track:6NPVjNh8Jhru9xOmyQigds',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/2UQrm3KoMSJ16a2PTUlx2E',
      },
      'href': 'https://api.spotify.com/v1/albums/2UQrm3KoMSJ16a2PTUlx2E',
      'id': '2UQrm3KoMSJ16a2PTUlx2E',
      'images': [
        {
          'height': 635,
          'url': 'https://i.scdn.co/image/47006f7fe178be2344dccd7800fd2893dd32eecf',
          'width': 640,
        },
        {
          'height': 298,
          'url': 'https://i.scdn.co/image/9a0e1a8eda52bbae6b90e0cc960504327b73b72d',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/b3fc81a516d5eceb2ee8cfafca1f2f00ec30672e',
          'width': 64,
        },
      ],
      'name': 'All Star Smash Hits',
      'type': 'album',
      'uri': 'spotify:album:2UQrm3KoMSJ16a2PTUlx2E',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2iEvnFsWxR0Syqu2JNopAd',
        },
        'href': 'https://api.spotify.com/v1/artists/2iEvnFsWxR0Syqu2JNopAd',
        'id': '2iEvnFsWxR0Syqu2JNopAd',
        'name': 'Smash Mouth',
        'type': 'artist',
        'uri': 'spotify:artist:2iEvnFsWxR0Syqu2JNopAd',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 183280,
    'explicit': false,
    'external_ids': {
      'isrc': 'USDW10110270',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/5M5mzimlah21xlC1rAuIuY',
    },
    'href': 'https://api.spotify.com/v1/tracks/5M5mzimlah21xlC1rAuIuY',
    'id': '5M5mzimlah21xlC1rAuIuY',
    'name': "I'm A Believer - Radio Edit",
    'popularity': 57,
    'preview_url': 'https://p.scdn.co/mp3-preview/85a7e4c249d1fe6aed45649a3503b1e9ae4902af',
    'track_number': 16,
    'type': 'track',
    'uri': 'spotify:track:5M5mzimlah21xlC1rAuIuY',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3VZhtobnayfWeRS5Nm2uSu',
      },
      'href': 'https://api.spotify.com/v1/albums/3VZhtobnayfWeRS5Nm2uSu',
      'id': '3VZhtobnayfWeRS5Nm2uSu',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/fa782f407a2e76a534ec768c660f7d9af1f898aa',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/3643c0586b73bcff389c50fa7a06ec335d1d4d81',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/98652707f65979b0fab89f5f2812022287e35397',
          'width': 64,
        },
      ],
      'name': 'We Love Disney',
      'type': 'album',
      'uri': 'spotify:album:3VZhtobnayfWeRS5Nm2uSu',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/4UXqAaa6dQYAk18Lv7PEgX',
        },
        'href': 'https://api.spotify.com/v1/artists/4UXqAaa6dQYAk18Lv7PEgX',
        'id': '4UXqAaa6dQYAk18Lv7PEgX',
        'name': 'Fall Out Boy',
        'type': 'artist',
        'uri': 'spotify:artist:4UXqAaa6dQYAk18Lv7PEgX',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 199173,
    'explicit': false,
    'external_ids': {
      'isrc': 'USUM71510154',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6zMNLIFrUss4qklFUdpzjp',
    },
    'href': 'https://api.spotify.com/v1/tracks/6zMNLIFrUss4qklFUdpzjp',
    'id': '6zMNLIFrUss4qklFUdpzjp',
    'name': "I Wan'na Be Like You (The Monkey Song) - From \"The Jungle Book\"",
    'popularity': 47,
    'preview_url': 'https://p.scdn.co/mp3-preview/fce85487d510940f7e0f2c2d3fa30f4dc6fae0cd',
    'track_number': 7,
    'type': 'track',
    'uri': 'spotify:track:6zMNLIFrUss4qklFUdpzjp',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'CR',
        'DO',
        'GT',
        'HN',
        'MX',
        'NI',
        'PA',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/6MdSPgHUFtMVDLYZEUysbu',
      },
      'href': 'https://api.spotify.com/v1/albums/6MdSPgHUFtMVDLYZEUysbu',
      'id': '6MdSPgHUFtMVDLYZEUysbu',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/e8d7ec2ee4dc4376f512b81e781193400c934550',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/612869d4a445fc57a80d0fdfb0c57e205651c512',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/e844bd5fd26c46dc56effb6bcf0b78f4f5f7592d',
          'width': 64,
        },
      ],
      'name': 'Mickey: The Very Best of Toni Basil',
      'type': 'album',
      'uri': 'spotify:album:6MdSPgHUFtMVDLYZEUysbu',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/59hMeIYY3k3NoX54rrVGPv',
        },
        'href': 'https://api.spotify.com/v1/artists/59hMeIYY3k3NoX54rrVGPv',
        'id': '59hMeIYY3k3NoX54rrVGPv',
        'name': 'Toni Basil',
        'type': 'artist',
        'uri': 'spotify:artist:59hMeIYY3k3NoX54rrVGPv',
      },
    ],
    'available_markets': [
      'CA',
      'CR',
      'DO',
      'GT',
      'HN',
      'MX',
      'NI',
      'PA',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 253199,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBCKK8175201',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/3wHnnLwYFYufUNVDVQvWrb',
    },
    'href': 'https://api.spotify.com/v1/tracks/3wHnnLwYFYufUNVDVQvWrb',
    'id': '3wHnnLwYFYufUNVDVQvWrb',
    'name': 'Mickey',
    'popularity': 53,
    'preview_url': 'https://p.scdn.co/mp3-preview/679246a011e9efca93921b0f2625f44414b65995',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:3wHnnLwYFYufUNVDVQvWrb',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/5BvgP623rtvlc0HDcpzquz',
      },
      'href': 'https://api.spotify.com/v1/albums/5BvgP623rtvlc0HDcpzquz',
      'id': '5BvgP623rtvlc0HDcpzquz',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/33080534f9716c159af3cc491162a3e8745e6d84',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/0a34d15c8d2011f585dcc0c30e15d1e83cbe9e1e',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/9c84f17be53a336eac917f3eb34913338030d548',
          'width': 64,
        },
      ],
      'name': 'Katy Perry - Teenage Dream: The Complete Confection',
      'type': 'album',
      'uri': 'spotify:album:5BvgP623rtvlc0HDcpzquz',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/6jJ0s89eD6GaHleKKya26X',
        },
        'href': 'https://api.spotify.com/v1/artists/6jJ0s89eD6GaHleKKya26X',
        'id': '6jJ0s89eD6GaHleKKya26X',
        'name': 'Katy Perry',
        'type': 'artist',
        'uri': 'spotify:artist:6jJ0s89eD6GaHleKKya26X',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 227880,
    'explicit': false,
    'external_ids': {
      'isrc': 'USCA21001262',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/4lCv7b86sLynZbXhfScfm2',
    },
    'href': 'https://api.spotify.com/v1/tracks/4lCv7b86sLynZbXhfScfm2',
    'id': '4lCv7b86sLynZbXhfScfm2',
    'name': 'Firework',
    'popularity': 77,
    'preview_url': 'https://p.scdn.co/mp3-preview/e407c359a54830601fee51f9f2fb969e1c5ba12b',
    'track_number': 4,
    'type': 'track',
    'uri': 'spotify:track:4lCv7b86sLynZbXhfScfm2',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/1MNvMtEmMMdBXZBDcFNcWj',
      },
      'href': 'https://api.spotify.com/v1/albums/1MNvMtEmMMdBXZBDcFNcWj',
      'id': '1MNvMtEmMMdBXZBDcFNcWj',
      'images': [
        {
          'height': 635,
          'url': 'https://i.scdn.co/image/a738528b13a030a0c0c6a4414aa5a8f84b8e095e',
          'width': 640,
        },
        {
          'height': 298,
          'url': 'https://i.scdn.co/image/139c966f69c6471868464ae3bb991b571154a9f7',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/d9fe1db9b478bc49e34cc8c33505e3f760e44183',
          'width': 64,
        },
      ],
      'name': 'Stronger (Deluxe Version)',
      'type': 'album',
      'uri': 'spotify:album:1MNvMtEmMMdBXZBDcFNcWj',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/3BmGtnKgCSGYIUhmivXKWX',
        },
        'href': 'https://api.spotify.com/v1/artists/3BmGtnKgCSGYIUhmivXKWX',
        'id': '3BmGtnKgCSGYIUhmivXKWX',
        'name': 'Kelly Clarkson',
        'type': 'artist',
        'uri': 'spotify:artist:3BmGtnKgCSGYIUhmivXKWX',
      },
    ],
    'available_markets': [
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 221946,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBCTA1100364',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6D60klaHqbCl9ySc8VcRss',
    },
    'href': 'https://api.spotify.com/v1/tracks/6D60klaHqbCl9ySc8VcRss',
    'id': '6D60klaHqbCl9ySc8VcRss',
    'name': "Stronger (What Doesn't Kill You)",
    'popularity': 63,
    'preview_url': 'https://p.scdn.co/mp3-preview/328bdd62e0e8f7f110cb546017ff3bf3042cc37a',
    'track_number': 2,
    'type': 'track',
    'uri': 'spotify:track:6D60klaHqbCl9ySc8VcRss',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3KzAvEXcqJKBF97HrXwlgf',
      },
      'href': 'https://api.spotify.com/v1/albums/3KzAvEXcqJKBF97HrXwlgf',
      'id': '3KzAvEXcqJKBF97HrXwlgf',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/1e6c3774deb8c44852ac169e03ce3f7a37c936af',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/aec67ae3a374ecf851665ad5cadccc0ac42c0ae8',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/f038b690d8e3a98aea1397010b838e464f38fa79',
          'width': 64,
        },
      ],
      'name': 'Please Please Me (Remastered)',
      'type': 'album',
      'uri': 'spotify:album:3KzAvEXcqJKBF97HrXwlgf',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/3WrFJ7ztbogyGnTHbHJFl2',
        },
        'href': 'https://api.spotify.com/v1/artists/3WrFJ7ztbogyGnTHbHJFl2',
        'id': '3WrFJ7ztbogyGnTHbHJFl2',
        'name': 'The Beatles',
        'type': 'artist',
        'uri': 'spotify:artist:3WrFJ7ztbogyGnTHbHJFl2',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 155226,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBAYE0601423',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/5ZBeML7Lf3FMEVviTyvi8l',
    },
    'href': 'https://api.spotify.com/v1/tracks/5ZBeML7Lf3FMEVviTyvi8l',
    'id': '5ZBeML7Lf3FMEVviTyvi8l',
    'name': 'Twist And Shout - Remastered',
    'popularity': 65,
    'preview_url': 'https://p.scdn.co/mp3-preview/b7e3bc96b46e4dcc22cec5d23337d2446cb0ab87',
    'track_number': 14,
    'type': 'track',
    'uri': 'spotify:track:5ZBeML7Lf3FMEVviTyvi8l',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'single',
      'available_markets': [
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/1NwX9DLDpQSsJrrRdU3dEN',
      },
      'href': 'https://api.spotify.com/v1/albums/1NwX9DLDpQSsJrrRdU3dEN',
      'id': '1NwX9DLDpQSsJrrRdU3dEN',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/43601d0cfb0a0dc6985d75b688cca21814176192',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/098c8f70105ab309cfa933c322c25c1db5720961',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/04389f7ca08396586bae201154d180fe682b732b',
          'width': 64,
        },
      ],
      'name': 'Footloose',
      'type': 'album',
      'uri': 'spotify:album:1NwX9DLDpQSsJrrRdU3dEN',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1UTPBmNbXNTittyMJrNkvw',
        },
        'href': 'https://api.spotify.com/v1/artists/1UTPBmNbXNTittyMJrNkvw',
        'id': '1UTPBmNbXNTittyMJrNkvw',
        'name': 'Blake Shelton',
        'type': 'artist',
        'uri': 'spotify:artist:1UTPBmNbXNTittyMJrNkvw',
      },
    ],
    'available_markets': [
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 218493,
    'explicit': false,
    'external_ids': {
      'isrc': 'USKLP1100065',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/4shPfi6RsJiwQtso2XFGiL',
    },
    'href': 'https://api.spotify.com/v1/tracks/4shPfi6RsJiwQtso2XFGiL',
    'id': '4shPfi6RsJiwQtso2XFGiL',
    'name': 'Footloose',
    'popularity': 51,
    'preview_url': 'https://p.scdn.co/mp3-preview/e990f01c8eb28575f515bea90633cd4cf7c20050',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:4shPfi6RsJiwQtso2XFGiL',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/36fdxiOzdlmsrHgGcfvqUJ',
      },
      'href': 'https://api.spotify.com/v1/albums/36fdxiOzdlmsrHgGcfvqUJ',
      'id': '36fdxiOzdlmsrHgGcfvqUJ',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/87662643aedb0983840c2072a2c1c19801c97c02',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/40b5d87ef6a57c70baa0fcbb880b0aa3dd3f4e10',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/cd88e305c55f7a9eb54e7db154ad3083a1e288ec',
          'width': 64,
        },
      ],
      'name': 'THE E.N.D. (THE ENERGY NEVER DIES)',
      'type': 'album',
      'uri': 'spotify:album:36fdxiOzdlmsrHgGcfvqUJ',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1yxSLGMDHlW21z4YXirZDS',
        },
        'href': 'https://api.spotify.com/v1/artists/1yxSLGMDHlW21z4YXirZDS',
        'id': '1yxSLGMDHlW21z4YXirZDS',
        'name': 'The Black Eyed Peas',
        'type': 'artist',
        'uri': 'spotify:artist:1yxSLGMDHlW21z4YXirZDS',
      },
    ],
    'available_markets': [
      'CA',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 289133,
    'explicit': false,
    'external_ids': {
      'isrc': 'USUM70965169',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/4vp2J1l5RD4gMZwGFLfRAu',
    },
    'href': 'https://api.spotify.com/v1/tracks/4vp2J1l5RD4gMZwGFLfRAu',
    'id': '4vp2J1l5RD4gMZwGFLfRAu',
    'name': 'I Gotta Feeling',
    'popularity': 66,
    'preview_url': 'https://p.scdn.co/mp3-preview/e7ec841b64d6101eff6e20fb69f8b540927f9207',
    'track_number': 5,
    'type': 'track',
    'uri': 'spotify:track:4vp2J1l5RD4gMZwGFLfRAu',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/159jpldDCgsgH6KGgjy63c',
      },
      'href': 'https://api.spotify.com/v1/albums/159jpldDCgsgH6KGgjy63c',
      'id': '159jpldDCgsgH6KGgjy63c',
      'images': [
        {
          'height': 633,
          'url': 'https://i.scdn.co/image/1786ca5b511633d9e4ca5b6b49686a6d37b4d707',
          'width': 640,
        },
        {
          'height': 297,
          'url': 'https://i.scdn.co/image/0629a9d68af3098b9933ac3f424e42c6a7d350d2',
          'width': 300,
        },
        {
          'height': 63,
          'url': 'https://i.scdn.co/image/65763be2d744ba2b4d088654bf06609d28d7d685',
          'width': 64,
        },
      ],
      'name': 'Rokstarr',
      'type': 'album',
      'uri': 'spotify:album:159jpldDCgsgH6KGgjy63c',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/6MF9fzBmfXghAz953czmBC',
        },
        'href': 'https://api.spotify.com/v1/artists/6MF9fzBmfXghAz953czmBC',
        'id': '6MF9fzBmfXghAz953czmBC',
        'name': 'Taio Cruz',
        'type': 'artist',
        'uri': 'spotify:artist:6MF9fzBmfXghAz953czmBC',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 203866,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBUM71003721',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/1DqdF42leyFIzqNDv9CjId',
    },
    'href': 'https://api.spotify.com/v1/tracks/1DqdF42leyFIzqNDv9CjId',
    'id': '1DqdF42leyFIzqNDv9CjId',
    'name': 'Dynamite',
    'popularity': 64,
    'preview_url': 'https://p.scdn.co/mp3-preview/7605d625f1425aedd7acfa2da88ea22434fb4d5d',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:1DqdF42leyFIzqNDv9CjId',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/6yPJmxBhq3zxj9gfTddfyU',
      },
      'href': 'https://api.spotify.com/v1/albums/6yPJmxBhq3zxj9gfTddfyU',
      'id': '6yPJmxBhq3zxj9gfTddfyU',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/3f43322b89e08ef8380f28c5eac193d1a5864c2f',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/ee0c12bf11b6f42e9bd88ed261cdb09ede860761',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/ee76acf375579d948429c252062764f7bcdfa4db',
          'width': 64,
        },
      ],
      'name': 'Fiesta Macarena',
      'type': 'album',
      'uri': 'spotify:album:6yPJmxBhq3zxj9gfTddfyU',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2JXn03fudjyRkQ1Ye9f5rk',
        },
        'href': 'https://api.spotify.com/v1/artists/2JXn03fudjyRkQ1Ye9f5rk',
        'id': '2JXn03fudjyRkQ1Ye9f5rk',
        'name': 'Los Del Rio',
        'type': 'artist',
        'uri': 'spotify:artist:2JXn03fudjyRkQ1Ye9f5rk',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 249506,
    'explicit': false,
    'external_ids': {
      'isrc': 'ES5109500538',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/4oaj36KzXRgDg4McgcTsZK',
    },
    'href': 'https://api.spotify.com/v1/tracks/4oaj36KzXRgDg4McgcTsZK',
    'id': '4oaj36KzXRgDg4McgcTsZK',
    'name': 'Macarena',
    'popularity': 53,
    'preview_url': 'https://p.scdn.co/mp3-preview/1f702250ec72803bfa1ee5e47a5d736087a3c7e8',
    'track_number': 12,
    'type': 'track',
    'uri': 'spotify:track:4oaj36KzXRgDg4McgcTsZK',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3kdp1PnxkKlshMP3qG2CUG',
      },
      'href': 'https://api.spotify.com/v1/albums/3kdp1PnxkKlshMP3qG2CUG',
      'id': '3kdp1PnxkKlshMP3qG2CUG',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/59fbc5e1ae93b6d0b90872c82d1245571af40fa0',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/89ec38c2c94511306e3bf6fafa9a8f183032a981',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/381afb68dc5690abd192633f811c88f2b48170a6',
          'width': 64,
        },
      ],
      'name': "Cruisin'",
      'type': 'album',
      'uri': 'spotify:album:3kdp1PnxkKlshMP3qG2CUG',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/0dCKce6tJJdHvlWnDMwzPW',
        },
        'href': 'https://api.spotify.com/v1/artists/0dCKce6tJJdHvlWnDMwzPW',
        'id': '0dCKce6tJJdHvlWnDMwzPW',
        'name': 'Village People',
        'type': 'artist',
        'uri': 'spotify:artist:0dCKce6tJJdHvlWnDMwzPW',
      },
    ],
    'available_markets': [
      'CA',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 286666,
    'explicit': false,
    'external_ids': {
      'isrc': 'USPR37800001',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/4YOJFyjqh8eAcbKFfv88mV',
    },
    'href': 'https://api.spotify.com/v1/tracks/4YOJFyjqh8eAcbKFfv88mV',
    'id': '4YOJFyjqh8eAcbKFfv88mV',
    'name': 'Y.M.C.A.',
    'popularity': 54,
    'preview_url': 'https://p.scdn.co/mp3-preview/d1d6f25c51646e52397a3d0fd68342bc5015318a',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:4YOJFyjqh8eAcbKFfv88mV',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/1tDyAU95D65Shy34JxsQCu',
      },
      'href': 'https://api.spotify.com/v1/albums/1tDyAU95D65Shy34JxsQCu',
      'id': '1tDyAU95D65Shy34JxsQCu',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/3216d190bc8b875775315b78fa18c822bb6c66e8',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/b0aec93d6891bd1d3883ff7e8de04bd627f3e3ea',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/610721b4f2237a3656d627b34db233bd135c75c4',
          'width': 64,
        },
      ],
      'name': 'Time For A Change',
      'type': 'album',
      'uri': 'spotify:album:1tDyAU95D65Shy34JxsQCu',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/0lax1ZgWclW6mZFaGu27MM',
        },
        'href': 'https://api.spotify.com/v1/artists/0lax1ZgWclW6mZFaGu27MM',
        'id': '0lax1ZgWclW6mZFaGu27MM',
        'name': 'Cupid',
        'type': 'artist',
        'uri': 'spotify:artist:0lax1ZgWclW6mZFaGu27MM',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 231360,
    'explicit': false,
    'external_ids': {
      'isrc': 'USAT20700490',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/07Tx168RSsUS1HqkDIOZbH',
    },
    'href': 'https://api.spotify.com/v1/tracks/07Tx168RSsUS1HqkDIOZbH',
    'id': '07Tx168RSsUS1HqkDIOZbH',
    'name': 'Cupid Shuffle',
    'popularity': 58,
    'preview_url': 'https://p.scdn.co/mp3-preview/d8ed1ba7c084b2c18be850ab8a77b5dd02456454',
    'track_number': 5,
    'type': 'track',
    'uri': 'spotify:track:07Tx168RSsUS1HqkDIOZbH',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/71amJ3G3bdLpCvDEoXzrLX',
      },
      'href': 'https://api.spotify.com/v1/albums/71amJ3G3bdLpCvDEoXzrLX',
      'id': '71amJ3G3bdLpCvDEoXzrLX',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/7a7f9b3c6a91479e73fa0cb8e4b270b7041da9d5',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/1984a9f82a4cc2a45bf1eac50a6c9a6aa829e102',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/5a75d9e2c287716ffea06cd986262c2be06a2a9f',
          'width': 64,
        },
      ],
      'name': 'Electric Slide Party',
      'type': 'album',
      'uri': 'spotify:album:71amJ3G3bdLpCvDEoXzrLX',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2GKYW7wLICTQuZ2qABEtWP',
        },
        'href': 'https://api.spotify.com/v1/artists/2GKYW7wLICTQuZ2qABEtWP',
        'id': '2GKYW7wLICTQuZ2qABEtWP',
        'name': 'Electric Slide Party',
        'type': 'artist',
        'uri': 'spotify:artist:2GKYW7wLICTQuZ2qABEtWP',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 222786,
    'explicit': false,
    'external_ids': {
      'isrc': 'USA371522037',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/3CRP0AuScrQ316bYZZfJZa',
    },
    'href': 'https://api.spotify.com/v1/tracks/3CRP0AuScrQ316bYZZfJZa',
    'id': '3CRP0AuScrQ316bYZZfJZa',
    'name': 'Cha Cha Slide',
    'popularity': 19,
    'preview_url': 'https://p.scdn.co/mp3-preview/ddb0c0d3ee6167627f3a20c053da8797a731944a',
    'track_number': 6,
    'type': 'track',
    'uri': 'spotify:track:3CRP0AuScrQ316bYZZfJZa',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/0OP47i79jrKw8XcUaEDxn8',
      },
      'href': 'https://api.spotify.com/v1/albums/0OP47i79jrKw8XcUaEDxn8',
      'id': '0OP47i79jrKw8XcUaEDxn8',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/b81afe8a519b54f32f23fd526d9a879659c9ca4a',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/8901bfdd8626cecc1b496b5d1a1b7590acfcbfe9',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/961af711cd675ce04cd795115bb74bbe8b5bffcc',
          'width': 64,
        },
      ],
      'name': 'Electric Slide: with friends...',
      'type': 'album',
      'uri': 'spotify:album:0OP47i79jrKw8XcUaEDxn8',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1VCtMJoDuOXAqX0rVG8xCe',
        },
        'href': 'https://api.spotify.com/v1/artists/1VCtMJoDuOXAqX0rVG8xCe',
        'id': '1VCtMJoDuOXAqX0rVG8xCe',
        'name': 'Electric Slide Music Makers',
        'type': 'artist',
        'uri': 'spotify:artist:1VCtMJoDuOXAqX0rVG8xCe',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 237653,
    'explicit': false,
    'external_ids': {
      'isrc': 'USA561067275',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/0VhsAybZAPC1O1oEpmOTvU',
    },
    'href': 'https://api.spotify.com/v1/tracks/0VhsAybZAPC1O1oEpmOTvU',
    'id': '0VhsAybZAPC1O1oEpmOTvU',
    'name': 'Electric Slide',
    'popularity': 36,
    'preview_url': 'https://p.scdn.co/mp3-preview/08dac9aadafff89889b7efc18e2e8f99c5831913',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:0VhsAybZAPC1O1oEpmOTvU',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3btVhknqDeGAEd1Qj7lL57',
      },
      'href': 'https://api.spotify.com/v1/albums/3btVhknqDeGAEd1Qj7lL57',
      'id': '3btVhknqDeGAEd1Qj7lL57',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/aa695769a003591911e34b4af4939e0a54775366',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/782afbed1001c706404b13bad0a62eea69a6dddf',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/f02a2fe4759ee5aabfd50f9ad52457501a279a68',
          'width': 64,
        },
      ],
      'name': 'ABC',
      'type': 'album',
      'uri': 'spotify:album:3btVhknqDeGAEd1Qj7lL57',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2iE18Oxc8YSumAU232n4rW',
        },
        'href': 'https://api.spotify.com/v1/artists/2iE18Oxc8YSumAU232n4rW',
        'id': '2iE18Oxc8YSumAU232n4rW',
        'name': 'The Jackson 5',
        'type': 'artist',
        'uri': 'spotify:artist:2iE18Oxc8YSumAU232n4rW',
      },
    ],
    'available_markets': [
      'CA',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 177733,
    'explicit': false,
    'external_ids': {
      'isrc': 'USMO17082628',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6wDviYDtmSDZ0S6TVMM9Vc',
    },
    'href': 'https://api.spotify.com/v1/tracks/6wDviYDtmSDZ0S6TVMM9Vc',
    'id': '6wDviYDtmSDZ0S6TVMM9Vc',
    'name': 'ABC',
    'popularity': 59,
    'preview_url': 'https://p.scdn.co/mp3-preview/18805083af5571fc672f9b99054348948f3afec4',
    'track_number': 3,
    'type': 'track',
    'uri': 'spotify:track:6wDviYDtmSDZ0S6TVMM9Vc',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'single',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/40LbnfieVTWtHrK24WQeEB',
      },
      'href': 'https://api.spotify.com/v1/albums/40LbnfieVTWtHrK24WQeEB',
      'id': '40LbnfieVTWtHrK24WQeEB',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/d013904153a1c3771a7f851132b090254c39a51b',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/84b9940cb99bf1072d553158c6e23426cb13b789',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/65234ee4a5155e1e9848d73c9a5d4167640c5442',
          'width': 64,
        },
      ],
      'name': "CAN'T STOP THE FEELING! (Original Song from DreamWorks Animation's \"TROLLS\")",
      'type': 'album',
      'uri': 'spotify:album:40LbnfieVTWtHrK24WQeEB',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/31TPClRtHm23RisEBtV3X7',
        },
        'href': 'https://api.spotify.com/v1/artists/31TPClRtHm23RisEBtV3X7',
        'id': '31TPClRtHm23RisEBtV3X7',
        'name': 'Justin Timberlake',
        'type': 'artist',
        'uri': 'spotify:artist:31TPClRtHm23RisEBtV3X7',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 236001,
    'explicit': false,
    'external_ids': {
      'isrc': 'USRC11600876',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6JV2JOEocMgcZxYSZelKcc',
    },
    'href': 'https://api.spotify.com/v1/tracks/6JV2JOEocMgcZxYSZelKcc',
    'id': '6JV2JOEocMgcZxYSZelKcc',
    'name': "CAN'T STOP THE FEELING! (Original Song from DreamWorks Animation's \"TROLLS\")",
    'popularity': 98,
    'preview_url': 'https://p.scdn.co/mp3-preview/9127f47e7e5265f51ab9e1a8d5d8edb9b7cb91a5',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:6JV2JOEocMgcZxYSZelKcc',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/7lpbyGc4fHsQkBTsfWVBhp',
      },
      'href': 'https://api.spotify.com/v1/albums/7lpbyGc4fHsQkBTsfWVBhp',
      'id': '7lpbyGc4fHsQkBTsfWVBhp',
      'images': [
        {
          'height': 574,
          'url': 'https://i.scdn.co/image/044340dd5b2147f9a877025888ddcb05aa049c3a',
          'width': 640,
        },
        {
          'height': 269,
          'url': 'https://i.scdn.co/image/158e41c4073a04340e30b30537d4a1ddc6fc0ad2',
          'width': 300,
        },
        {
          'height': 57,
          'url': 'https://i.scdn.co/image/a15e2428f234ffe0f0a6117d3630aa9655ac7017',
          'width': 64,
        },
      ],
      'name': 'The Blessed Unrest',
      'type': 'album',
      'uri': 'spotify:album:7lpbyGc4fHsQkBTsfWVBhp',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2Sqr0DXoaYABbjBo9HaMkM',
        },
        'href': 'https://api.spotify.com/v1/artists/2Sqr0DXoaYABbjBo9HaMkM',
        'id': '2Sqr0DXoaYABbjBo9HaMkM',
        'name': 'Sara Bareilles',
        'type': 'artist',
        'uri': 'spotify:artist:2Sqr0DXoaYABbjBo9HaMkM',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 220573,
    'explicit': false,
    'external_ids': {
      'isrc': 'USSM11301638',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6Uy6K3KdmUdAfelUp0SeXn',
    },
    'href': 'https://api.spotify.com/v1/tracks/6Uy6K3KdmUdAfelUp0SeXn',
    'id': '6Uy6K3KdmUdAfelUp0SeXn',
    'name': 'Brave',
    'popularity': 72,
    'preview_url': 'https://p.scdn.co/mp3-preview/20cffa039f5579b6202442d5cbe90a7f14bcda7f',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:6Uy6K3KdmUdAfelUp0SeXn',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'single',
      'available_markets': [
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3eHEUyFhVdkoXEJzXC0EKT',
      },
      'href': 'https://api.spotify.com/v1/albums/3eHEUyFhVdkoXEJzXC0EKT',
      'id': '3eHEUyFhVdkoXEJzXC0EKT',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/f733ed9c963e0e4f3e8dfd08ee739e8998836259',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/d5865f1b3493e2696601d2c0cf2ff864c41594fe',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/c3ffea4c81345116b5f9c2e7457897c25c7a4b0f',
          'width': 64,
        },
      ],
      'name': 'Call Me Maybe',
      'type': 'album',
      'uri': 'spotify:album:3eHEUyFhVdkoXEJzXC0EKT',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/6sFIWsNpZYqfjUpaCgueju',
        },
        'href': 'https://api.spotify.com/v1/artists/6sFIWsNpZYqfjUpaCgueju',
        'id': '6sFIWsNpZYqfjUpaCgueju',
        'name': 'Carly Rae Jepsen',
        'type': 'artist',
        'uri': 'spotify:artist:6sFIWsNpZYqfjUpaCgueju',
      },
    ],
    'available_markets': [
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 193466,
    'explicit': false,
    'external_ids': {
      'isrc': 'CAB391100615',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6ol4ZSifr7r3Lb2a9L5ZAB',
    },
    'href': 'https://api.spotify.com/v1/tracks/6ol4ZSifr7r3Lb2a9L5ZAB',
    'id': '6ol4ZSifr7r3Lb2a9L5ZAB',
    'name': 'Call Me Maybe',
    'popularity': 63,
    'preview_url': 'https://p.scdn.co/mp3-preview/9e00c551bf032195d93c04e712e093f1f300b766',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:6ol4ZSifr7r3Lb2a9L5ZAB',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/2bbhW5ifCwOYM8DMkqoYBF',
      },
      'href': 'https://api.spotify.com/v1/albums/2bbhW5ifCwOYM8DMkqoYBF',
      'id': '2bbhW5ifCwOYM8DMkqoYBF',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/8b6238186da6c5c9b0ff756065883aa1a8fbd339',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/3f4ed4e1bfe1acc966762ca838b49e2c3550a1c0',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/29e961f88981da505ba8f7290db2a568c2a1e428',
          'width': 64,
        },
      ],
      'name': 'Native',
      'type': 'album',
      'uri': 'spotify:album:2bbhW5ifCwOYM8DMkqoYBF',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/5Pwc4xIPtQLFEnJriah9YJ',
        },
        'href': 'https://api.spotify.com/v1/artists/5Pwc4xIPtQLFEnJriah9YJ',
        'id': '5Pwc4xIPtQLFEnJriah9YJ',
        'name': 'OneRepublic',
        'type': 'artist',
        'uri': 'spotify:artist:5Pwc4xIPtQLFEnJriah9YJ',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 224226,
    'explicit': false,
    'external_ids': {
      'isrc': 'USUM71404631',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/5BJSZocnCeSNeYMj3iVqM7',
    },
    'href': 'https://api.spotify.com/v1/tracks/5BJSZocnCeSNeYMj3iVqM7',
    'id': '5BJSZocnCeSNeYMj3iVqM7',
    'name': 'Love Runs Out',
    'popularity': 65,
    'preview_url': 'https://p.scdn.co/mp3-preview/91057700a424f4de6e7f3f927382d62fb6479d4f',
    'track_number': 2,
    'type': 'track',
    'uri': 'spotify:track:5BJSZocnCeSNeYMj3iVqM7',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/2G4AUqfwxcV1UdQjm2ouYr',
      },
      'href': 'https://api.spotify.com/v1/albums/2G4AUqfwxcV1UdQjm2ouYr',
      'id': '2G4AUqfwxcV1UdQjm2ouYr',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/6218fc701d5c6e66c200f29b57fc4cd5f979313f',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/29ce98b4349b72c2778d2f82823159b06f98f8bc',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/4af48c1b31d3e2a2f6304226bb2e258e38541dbb',
          'width': 64,
        },
      ],
      'name': 'Ghost Stories',
      'type': 'album',
      'uri': 'spotify:album:2G4AUqfwxcV1UdQjm2ouYr',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/4gzpq5DPGxSnKTe4SA8HAU',
        },
        'href': 'https://api.spotify.com/v1/artists/4gzpq5DPGxSnKTe4SA8HAU',
        'id': '4gzpq5DPGxSnKTe4SA8HAU',
        'name': 'Coldplay',
        'type': 'artist',
        'uri': 'spotify:artist:4gzpq5DPGxSnKTe4SA8HAU',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 268466,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBAYE1400217',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/0FDzzruyVECATHXKHFs9eJ',
    },
    'href': 'https://api.spotify.com/v1/tracks/0FDzzruyVECATHXKHFs9eJ',
    'id': '0FDzzruyVECATHXKHFs9eJ',
    'name': 'A Sky Full of Stars',
    'popularity': 81,
    'preview_url': 'https://p.scdn.co/mp3-preview/dca7402083b8dbf0e2a5e91f49eb76bde94cd493',
    'track_number': 8,
    'type': 'track',
    'uri': 'spotify:track:0FDzzruyVECATHXKHFs9eJ',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/7npBPiCHjPj8PVIGPuHXep',
      },
      'href': 'https://api.spotify.com/v1/albums/7npBPiCHjPj8PVIGPuHXep',
      'id': '7npBPiCHjPj8PVIGPuHXep',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/443338f82fb889e262938b0aedcc278c2035fd39',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/e44412a1609d9ef79ef45afaa1d88122b5c307aa',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/af2682d292fc31aab6c58f12d5c1d45c190285be',
          'width': 64,
        },
      ],
      'name': 'Paul Simon',
      'type': 'album',
      'uri': 'spotify:album:7npBPiCHjPj8PVIGPuHXep',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2CvCyf1gEVhI0mX6aFXmVI',
        },
        'href': 'https://api.spotify.com/v1/artists/2CvCyf1gEVhI0mX6aFXmVI',
        'id': '2CvCyf1gEVhI0mX6aFXmVI',
        'name': 'Paul Simon',
        'type': 'artist',
        'uri': 'spotify:artist:2CvCyf1gEVhI0mX6aFXmVI',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 164813,
    'explicit': false,
    'external_ids': {
      'isrc': 'USSM11002239',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/6vxHp3CDNo0afgKGp2yi1E',
    },
    'href': 'https://api.spotify.com/v1/tracks/6vxHp3CDNo0afgKGp2yi1E',
    'id': '6vxHp3CDNo0afgKGp2yi1E',
    'name': 'Me and Julio Down by the Schoolyard',
    'popularity': 69,
    'preview_url': 'https://p.scdn.co/mp3-preview/902633811e6a135bdd9ece72e92318e2ce2fe509',
    'track_number': 6,
    'type': 'track',
    'uri': 'spotify:track:6vxHp3CDNo0afgKGp2yi1E',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/64fQ94AVziavTPdnkCS6Nj',
      },
      'href': 'https://api.spotify.com/v1/albums/64fQ94AVziavTPdnkCS6Nj',
      'id': '64fQ94AVziavTPdnkCS6Nj',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/4627f2fcd0f5299bb8577ddbe26a5e919095c781',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/f823241969b5dae21fa03d34252842609ba9e2ea',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/c011f00b99131631c73bd69f49e24c2246a1f6d4',
          'width': 64,
        },
      ],
      'name': 'Bad Blood',
      'type': 'album',
      'uri': 'spotify:album:64fQ94AVziavTPdnkCS6Nj',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/7EQ0qTo7fWT7DPxmxtSYEc',
        },
        'href': 'https://api.spotify.com/v1/artists/7EQ0qTo7fWT7DPxmxtSYEc',
        'id': '7EQ0qTo7fWT7DPxmxtSYEc',
        'name': 'Bastille',
        'type': 'artist',
        'uri': 'spotify:artist:7EQ0qTo7fWT7DPxmxtSYEc',
      },
    ],
    'available_markets': [
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 214147,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBAAA1200795',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/3gbBpTdY8lnQwqxNCcf795',
    },
    'href': 'https://api.spotify.com/v1/tracks/3gbBpTdY8lnQwqxNCcf795',
    'id': '3gbBpTdY8lnQwqxNCcf795',
    'name': 'Pompeii',
    'popularity': 72,
    'preview_url': 'https://p.scdn.co/mp3-preview/bbc1e33c92519556df22cb1193e68e10780a86e0',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:3gbBpTdY8lnQwqxNCcf795',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/3r4KvV3xbEN0VAHthWYnAE',
      },
      'href': 'https://api.spotify.com/v1/albums/3r4KvV3xbEN0VAHthWYnAE',
      'id': '3r4KvV3xbEN0VAHthWYnAE',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/39d8a9da23587f0273faad72797a27b77f5c8e07',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/1096b6e393642edd5f90c792971c2d92ea73109f',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/5a29454264d0011b84bbff183d58048fd3b9f8fd',
          'width': 64,
        },
      ],
      'name': 'Paradas Continuas',
      'type': 'album',
      'uri': 'spotify:album:3r4KvV3xbEN0VAHthWYnAE',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/0lwRI7lvmlRY5DiA5Xa6wQ',
        },
        'href': 'https://api.spotify.com/v1/artists/0lwRI7lvmlRY5DiA5Xa6wQ',
        'id': '0lwRI7lvmlRY5DiA5Xa6wQ',
        'name': 'Lipps Inc.',
        'type': 'artist',
        'uri': 'spotify:artist:0lwRI7lvmlRY5DiA5Xa6wQ',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 239253,
    'explicit': true,
    'external_ids': {
      'isrc': 'MX1900900138',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/7723JnKU2R15Iv4T7OJrly',
    },
    'href': 'https://api.spotify.com/v1/tracks/7723JnKU2R15Iv4T7OJrly',
    'id': '7723JnKU2R15Iv4T7OJrly',
    'name': 'Funky Town',
    'popularity': 63,
    'preview_url': 'https://p.scdn.co/mp3-preview/7378227189ebb06cc3bf9fdc99bfc6490843de9d',
    'track_number': 8,
    'type': 'track',
    'uri': 'spotify:track:7723JnKU2R15Iv4T7OJrly',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/1MbBSfcqLg2OjkeZ1RMSIq',
      },
      'href': 'https://api.spotify.com/v1/albums/1MbBSfcqLg2OjkeZ1RMSIq',
      'id': '1MbBSfcqLg2OjkeZ1RMSIq',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/cc8b0da17d22c8a0e83ff102e3007d60427cb1f8',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/4bee20dfe614a541e74ac5539527e1fcc6183a66',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/2c442c5c400c504c045a836aa4a4c8778c61517e',
          'width': 64,
        },
      ],
      'name': 'Sorry For Party Rocking (Edited Version)',
      'type': 'album',
      'uri': 'spotify:album:1MbBSfcqLg2OjkeZ1RMSIq',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/3sgFRtyBnxXD5ESfmbK4dl',
        },
        'href': 'https://api.spotify.com/v1/artists/3sgFRtyBnxXD5ESfmbK4dl',
        'id': '3sgFRtyBnxXD5ESfmbK4dl',
        'name': 'LMFAO',
        'type': 'artist',
        'uri': 'spotify:artist:3sgFRtyBnxXD5ESfmbK4dl',
      },
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/2jLE4BoXHriQ96JagEtiDP',
        },
        'href': 'https://api.spotify.com/v1/artists/2jLE4BoXHriQ96JagEtiDP',
        'id': '2jLE4BoXHriQ96JagEtiDP',
        'name': 'Lauren Bennett',
        'type': 'artist',
        'uri': 'spotify:artist:2jLE4BoXHriQ96JagEtiDP',
      },
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/53sIBaVjXQhfH89Vu6nEGh',
        },
        'href': 'https://api.spotify.com/v1/artists/53sIBaVjXQhfH89Vu6nEGh',
        'id': '53sIBaVjXQhfH89Vu6nEGh',
        'name': 'GoonRock',
        'type': 'artist',
        'uri': 'spotify:artist:53sIBaVjXQhfH89Vu6nEGh',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 262173,
    'explicit': false,
    'external_ids': {
      'isrc': 'USUM71100061',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/0IkKz2J93C94Ei4BvDop7P',
    },
    'href': 'https://api.spotify.com/v1/tracks/0IkKz2J93C94Ei4BvDop7P',
    'id': '0IkKz2J93C94Ei4BvDop7P',
    'name': 'Party Rock Anthem',
    'popularity': 62,
    'preview_url': 'https://p.scdn.co/mp3-preview/cb3e9ef87d8a272868dbf23280ef6902f330a041',
    'track_number': 3,
    'type': 'track',
    'uri': 'spotify:track:0IkKz2J93C94Ei4BvDop7P',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'compilation',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/5pfpXvoJtSIFrbPIoBEv3R',
      },
      'href': 'https://api.spotify.com/v1/albums/5pfpXvoJtSIFrbPIoBEv3R',
      'id': '5pfpXvoJtSIFrbPIoBEv3R',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/eb669772a583cba3fac0a9d5368bcdf3cb6a6fff',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/75017712a06dcae7832988046cd9aa280a4055f5',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/e81bf453c230fbaef3bb7eadd7aea766e6c2a707',
          'width': 64,
        },
      ],
      'name': 'The Essential Journey',
      'type': 'album',
      'uri': 'spotify:album:5pfpXvoJtSIFrbPIoBEv3R',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/0rvjqX7ttXeg3mTy8Xscbt',
        },
        'href': 'https://api.spotify.com/v1/artists/0rvjqX7ttXeg3mTy8Xscbt',
        'id': '0rvjqX7ttXeg3mTy8Xscbt',
        'name': 'Journey',
        'type': 'artist',
        'uri': 'spotify:artist:0rvjqX7ttXeg3mTy8Xscbt',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 248906,
    'explicit': false,
    'external_ids': {
      'isrc': 'USSM18100116',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/77NNZQSqzLNqh2A9JhLRkg',
    },
    'href': 'https://api.spotify.com/v1/tracks/77NNZQSqzLNqh2A9JhLRkg',
    'id': '77NNZQSqzLNqh2A9JhLRkg',
    'name': "Don't Stop Believin'",
    'popularity': 77,
    'preview_url': 'https://p.scdn.co/mp3-preview/5908f4536c2b1111045c46555811fe61112d5c26',
    'track_number': 2,
    'type': 'track',
    'uri': 'spotify:track:77NNZQSqzLNqh2A9JhLRkg',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/02rPed1mPkw2OtFpj6g4uV',
      },
      'href': 'https://api.spotify.com/v1/albums/02rPed1mPkw2OtFpj6g4uV',
      'id': '02rPed1mPkw2OtFpj6g4uV',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/c58666f33acd9c2f276b13eaafc6f7ab04dff320',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/efda6aacb8b8f76fd97a570ac4a2c6d9bc86e916',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/ea08ccb5c10748378a10ce8fac9f26172093dd92',
          'width': 64,
        },
      ],
      'name': 'The Soul of the Kung Fu Fighter',
      'type': 'album',
      'uri': 'spotify:album:02rPed1mPkw2OtFpj6g4uV',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/5Pqx4mXYDGIDcg8E5FYjZ8',
        },
        'href': 'https://api.spotify.com/v1/artists/5Pqx4mXYDGIDcg8E5FYjZ8',
        'id': '5Pqx4mXYDGIDcg8E5FYjZ8',
        'name': 'Carl Douglas',
        'type': 'artist',
        'uri': 'spotify:artist:5Pqx4mXYDGIDcg8E5FYjZ8',
      },
    ],
    'available_markets': [
      'CA',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 197693,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBAJE7400014',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/40hgbG1iX08Apyy0FesR7p',
    },
    'href': 'https://api.spotify.com/v1/tracks/40hgbG1iX08Apyy0FesR7p',
    'id': '40hgbG1iX08Apyy0FesR7p',
    'name': 'Kung Fu Fighting',
    'popularity': 59,
    'preview_url': 'https://p.scdn.co/mp3-preview/c0bcf18532290f37d42a25dc1d4e973360c9b575',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:40hgbG1iX08Apyy0FesR7p',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/44UH34qoCNNfEqo0VnOkGd',
      },
      'href': 'https://api.spotify.com/v1/albums/44UH34qoCNNfEqo0VnOkGd',
      'id': '44UH34qoCNNfEqo0VnOkGd',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/47877ab9657444d364e65da1311cbe873712845a',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/87d0a31608262aaf03ec74b874e9608d4d1ecdec',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/fb32102bbc28c430783c2e42dfb529e00d378613',
          'width': 64,
        },
      ],
      'name': 'Who Let The Dogs Out',
      'type': 'album',
      'uri': 'spotify:album:44UH34qoCNNfEqo0VnOkGd',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/67FFKYikvTlvsPNk4NPOYJ',
        },
        'href': 'https://api.spotify.com/v1/artists/67FFKYikvTlvsPNk4NPOYJ',
        'id': '67FFKYikvTlvsPNk4NPOYJ',
        'name': 'Baha Men',
        'type': 'artist',
        'uri': 'spotify:artist:67FFKYikvTlvsPNk4NPOYJ',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 198400,
    'explicit': false,
    'external_ids': {
      'isrc': 'USSC90000001',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/1H5tvpoApNDxvxDexoaAUo',
    },
    'href': 'https://api.spotify.com/v1/tracks/1H5tvpoApNDxvxDexoaAUo',
    'id': '1H5tvpoApNDxvxDexoaAUo',
    'name': 'Who Let The Dogs Out',
    'popularity': 61,
    'preview_url': 'https://p.scdn.co/mp3-preview/2d508a24709fa835647b18fdd559d3e4cbb6ac1f',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:1H5tvpoApNDxvxDexoaAUo',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/4oVG376KpWeBaxrKqRxVri',
      },
      'href': 'https://api.spotify.com/v1/albums/4oVG376KpWeBaxrKqRxVri',
      'id': '4oVG376KpWeBaxrKqRxVri',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/5031974d62fe1ef31b7678343e3ad4d11d922131',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/bcc0d93bc3792c863f024c49d7dacf7fa77f17ed',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/a0c5959568db3df177d7a990edeead081bb2f20d',
          'width': 64,
        },
      ],
      'name': 'Lights',
      'type': 'album',
      'uri': 'spotify:album:4oVG376KpWeBaxrKqRxVri',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/0X2BH1fck6amBIoJhDVmmJ',
        },
        'href': 'https://api.spotify.com/v1/artists/0X2BH1fck6amBIoJhDVmmJ',
        'id': '0X2BH1fck6amBIoJhDVmmJ',
        'name': 'Ellie Goulding',
        'type': 'artist',
        'uri': 'spotify:artist:0X2BH1fck6amBIoJhDVmmJ',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 211800,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBUM71028043',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/7gUpO6td4OOnu0Lf9vhcIV',
    },
    'href': 'https://api.spotify.com/v1/tracks/7gUpO6td4OOnu0Lf9vhcIV',
    'id': '7gUpO6td4OOnu0Lf9vhcIV',
    'name': 'Lights - Single Version',
    'popularity': 65,
    'preview_url': 'https://p.scdn.co/mp3-preview/b1a8c57fd81f840e0e1471999710766f4d03d029',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:7gUpO6td4OOnu0Lf9vhcIV',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'compilation',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/79F4jBcsI4qg66Xax1u4U8',
      },
      'href': 'https://api.spotify.com/v1/albums/79F4jBcsI4qg66Xax1u4U8',
      'id': '79F4jBcsI4qg66Xax1u4U8',
      'images': [
        {
          'height': 628,
          'url': 'https://i.scdn.co/image/7b24537bef081dc676faf024640f92db9f3536ed',
          'width': 640,
        },
        {
          'height': 294,
          'url': 'https://i.scdn.co/image/ccd143ea9a837f95f0ff44e730a6e749f3de4ebc',
          'width': 300,
        },
        {
          'height': 63,
          'url': 'https://i.scdn.co/image/b050ae7006c7a2aeceafa0cbb3c6b16825edf01d',
          'width': 64,
        },
      ],
      'name': 'Number Ones',
      'type': 'album',
      'uri': 'spotify:album:79F4jBcsI4qg66Xax1u4U8',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1LZEQNv7sE11VDY3SdxQeN',
        },
        'href': 'https://api.spotify.com/v1/artists/1LZEQNv7sE11VDY3SdxQeN',
        'id': '1LZEQNv7sE11VDY3SdxQeN',
        'name': 'Bee Gees',
        'type': 'artist',
        'uri': 'spotify:artist:1LZEQNv7sE11VDY3SdxQeN',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 285200,
    'explicit': false,
    'external_ids': {
      'isrc': 'USRH10650365',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/3LmpQiFNgFCnvAnhhvKUyI',
    },
    'href': 'https://api.spotify.com/v1/tracks/3LmpQiFNgFCnvAnhhvKUyI',
    'id': '3LmpQiFNgFCnvAnhhvKUyI',
    'name': "Stayin' Alive (Remastered Album Version)",
    'popularity': 70,
    'preview_url': 'https://p.scdn.co/mp3-preview/3d1632a9d561aa44fd5d66eb766e002cb2acf6d0',
    'track_number': 11,
    'type': 'track',
    'uri': 'spotify:track:3LmpQiFNgFCnvAnhhvKUyI',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'EE',
        'SV',
        'FI',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LV',
        'LT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'SE',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/1C2h7mLntPSeVYciMRTF4a',
      },
      'href': 'https://api.spotify.com/v1/albums/1C2h7mLntPSeVYciMRTF4a',
      'id': '1C2h7mLntPSeVYciMRTF4a',
      'images': [
        {
          'height': 568,
          'url': 'https://i.scdn.co/image/3c294000d8739af300d9a842934d6f7e090471c7',
          'width': 640,
        },
        {
          'height': 266,
          'url': 'https://i.scdn.co/image/d50dab8e3338d47ddc84195a0779b6b80704f8c5',
          'width': 300,
        },
        {
          'height': 57,
          'url': 'https://i.scdn.co/image/eb2b6bb819fd2b1795acd65efc8e1a975c487afc',
          'width': 64,
        },
      ],
      'name': 'Thriller 25 Super Deluxe Edition',
      'type': 'album',
      'uri': 'spotify:album:1C2h7mLntPSeVYciMRTF4a',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/3fMbdgg4jU18AjLCKBhRSm',
        },
        'href': 'https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm',
        'id': '3fMbdgg4jU18AjLCKBhRSm',
        'name': 'Michael Jackson',
        'type': 'artist',
        'uri': 'spotify:artist:3fMbdgg4jU18AjLCKBhRSm',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'EE',
      'SV',
      'FI',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'SE',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 293826,
    'explicit': false,
    'external_ids': {
      'isrc': 'USSM19902991',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5',
    },
    'href': 'https://api.spotify.com/v1/tracks/5ChkMS8OtdzJeqyybCc9R5',
    'id': '5ChkMS8OtdzJeqyybCc9R5',
    'name': 'Billie Jean - Single Version',
    'popularity': 78,
    'preview_url': 'https://p.scdn.co/mp3-preview/4eb779428d40d579f14d12a9daf98fc66c7d0be4',
    'track_number': 6,
    'type': 'track',
    'uri': 'spotify:track:5ChkMS8OtdzJeqyybCc9R5',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'single',
      'available_markets': [
        'AR',
        'AU',
        'AT',
        'BE',
        'BO',
        'BR',
        'BG',
        'CA',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DK',
        'DO',
        'DE',
        'EC',
        'SV',
        'FR',
        'GR',
        'GT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IE',
        'IT',
        'LU',
        'MY',
        'MT',
        'MX',
        'NL',
        'NZ',
        'NI',
        'NO',
        'PA',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'SG',
        'SK',
        'ES',
        'CH',
        'TW',
        'TR',
        'UY',
        'US',
        'GB',
        'AD',
        'LI',
        'MC',
        'ID',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/7LnU0hAOYe9aq91PCKMI7A',
      },
      'href': 'https://api.spotify.com/v1/albums/7LnU0hAOYe9aq91PCKMI7A',
      'id': '7LnU0hAOYe9aq91PCKMI7A',
      'images': [
        {
          'height': 640,
          'url': 'https://i.scdn.co/image/bd6dffbcab8963ee5a2b15b58f861918caaa6d43',
          'width': 640,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/dd5fc5228adcd7049373e3c925259f6a4a5978b0',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/286f561d1e2e97f0de82dae9f09e51af8161d3b5',
          'width': 64,
        },
      ],
      'name': 'Drag Me Down',
      'type': 'album',
      'uri': 'spotify:album:7LnU0hAOYe9aq91PCKMI7A',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/4AK6F7OLvEQ5QYCBNiQWHq',
        },
        'href': 'https://api.spotify.com/v1/artists/4AK6F7OLvEQ5QYCBNiQWHq',
        'id': '4AK6F7OLvEQ5QYCBNiQWHq',
        'name': 'One Direction',
        'type': 'artist',
        'uri': 'spotify:artist:4AK6F7OLvEQ5QYCBNiQWHq',
      },
    ],
    'available_markets': [
      'AR',
      'AU',
      'AT',
      'BE',
      'BO',
      'BR',
      'BG',
      'CA',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DK',
      'DO',
      'DE',
      'EC',
      'SV',
      'FR',
      'GR',
      'GT',
      'HN',
      'HK',
      'HU',
      'IS',
      'IE',
      'IT',
      'LU',
      'MY',
      'MT',
      'MX',
      'NL',
      'NZ',
      'NI',
      'NO',
      'PA',
      'PY',
      'PE',
      'PH',
      'PL',
      'PT',
      'SG',
      'SK',
      'ES',
      'CH',
      'TW',
      'TR',
      'UY',
      'US',
      'GB',
      'AD',
      'LI',
      'MC',
      'ID',
    ],
    'disc_number': 1,
    'duration_ms': 192106,
    'explicit': false,
    'external_ids': {
      'isrc': 'GBHMU1500070',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/70OTIpw8x8UXUsuCHW9i1i',
    },
    'href': 'https://api.spotify.com/v1/tracks/70OTIpw8x8UXUsuCHW9i1i',
    'id': '70OTIpw8x8UXUsuCHW9i1i',
    'name': 'Drag Me Down',
    'popularity': 74,
    'preview_url': 'https://p.scdn.co/mp3-preview/4aa177e8654638553a90eafb7eafc0806441f112',
    'track_number': 1,
    'type': 'track',
    'uri': 'spotify:track:70OTIpw8x8UXUsuCHW9i1i',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
  {
    'album': {
      'album_type': 'album',
      'available_markets': [
        'CA',
        'MX',
        'US',
      ],
      'external_urls': {
        'spotify': 'https://open.spotify.com/album/7strNUlU6xZqlVWBNUdOYv',
      },
      'href': 'https://api.spotify.com/v1/albums/7strNUlU6xZqlVWBNUdOYv',
      'id': '7strNUlU6xZqlVWBNUdOYv',
      'images': [
        {
          'height': 600,
          'url': 'https://i.scdn.co/image/9fdc2291845d5b4970e001dc3da87ffce7e4f255',
          'width': 600,
        },
        {
          'height': 300,
          'url': 'https://i.scdn.co/image/16e1ac8080bfec1f83a99dfaf8223daa89fbce2b',
          'width': 300,
        },
        {
          'height': 64,
          'url': 'https://i.scdn.co/image/59fe88fe31ce95a07ef0d12a6673b784458d7a69',
          'width': 64,
        },
      ],
      'name': 'Hands All Over',
      'type': 'album',
      'uri': 'spotify:album:7strNUlU6xZqlVWBNUdOYv',
    },
    'artists': [
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/04gDigrS5kc9YWfZHwBETP',
        },
        'href': 'https://api.spotify.com/v1/artists/04gDigrS5kc9YWfZHwBETP',
        'id': '04gDigrS5kc9YWfZHwBETP',
        'name': 'Maroon 5',
        'type': 'artist',
        'uri': 'spotify:artist:04gDigrS5kc9YWfZHwBETP',
      },
      {
        'external_urls': {
          'spotify': 'https://open.spotify.com/artist/1l7ZsJRRS8wlW3WfJfPfNS',
        },
        'href': 'https://api.spotify.com/v1/artists/1l7ZsJRRS8wlW3WfJfPfNS',
        'id': '1l7ZsJRRS8wlW3WfJfPfNS',
        'name': 'Christina Aguilera',
        'type': 'artist',
        'uri': 'spotify:artist:1l7ZsJRRS8wlW3WfJfPfNS',
      },
    ],
    'available_markets': [
      'CA',
      'MX',
      'US',
    ],
    'disc_number': 1,
    'duration_ms': 201160,
    'explicit': false,
    'external_ids': {
      'isrc': 'USUM71109132',
    },
    'external_urls': {
      'spotify': 'https://open.spotify.com/track/7LcfRTgAVTs5pQGEQgUEzN',
    },
    'href': 'https://api.spotify.com/v1/tracks/7LcfRTgAVTs5pQGEQgUEzN',
    'id': '7LcfRTgAVTs5pQGEQgUEzN',
    'name': 'Moves Like Jagger - Studio Recording From The Voice Performance',
    'popularity': 72,
    'preview_url': 'https://p.scdn.co/mp3-preview/b7a41ee81f1059e6d470b2215ba08d6dc697eaa1',
    'track_number': 13,
    'type': 'track',
    'uri': 'spotify:track:7LcfRTgAVTs5pQGEQgUEzN',
    'votes': [
      '70d78f26-51a5-4073-8b3e-1b273b559b01',
    ],
    'votesCount': 1,
  },
];

export default () => tracks[Math.floor(Math.random() * tracks.length)];
